services:
  mvp_bot:
    build: .
    container_name: mvp_bot_container
    ports:
      - "8080:8080" 
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    volumes:
      - .:/app 
    restart: always
    env_file:
      - .env
