name: Continuous Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - 'test'

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23.3'

      - name: Build the bot
        run: go build -o bot/main bot/main.go

      - name: Deploy to server
        run: |
          echo "Deploying to server..."
          scp -i ${{ secrets.SSH_PRIVATE_KEY }} bot/main user@your-server:/path/to/deploy
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} user@your-server 'bash -s' < deploy_script.sh
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
