name: Deploy Project

on:
  push:
    branches:
      - '*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23.3'

      - name: Install dependencies
        run: go mod tidy

      - name: Build the project
        run: go build -o bot/main bot/main.go

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Ваш приватный ключ, настроенный в Secrets

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no user@your-server.com << 'EOF'
            cd /path/to/your/project
            git pull origin main  # Обновление кода на сервере
            go mod tidy  # Обновление зависимостей
            go build -o bot/main bot/main.go  # Сборка на сервере
            systemctl restart bot.service  # Перезапуск вашего сервиса, если используется systemd
          EOF
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

