name: Documentation Generation

on:
  push:
    branches:
      - main
      - develop
      - test

jobs:
  generate_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23.3'

      - name: Generate Go documentation
        run: go doc ./...
