name: Documentation Generation

on:
  workflow_dispatch:
  push:
    branches:
      - 'test'

jobs:
  generate_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23.3'

      - name: Install GoDoc tool (optional)
        run: |
          go install golang.org/x/tools/cmd/godoc@latest

      - name: Generate Go documentation
        run: |
          echo "Generating documentation..."
          godoc -http=:6060 &
          curl http://localhost:6060/pkg/ > docs.html
          
      - name: Upload generated docs as artifact
        uses: actions/upload-artifact@v3
        with:
          name: go-docs
          path: docs.html
