name: Notify on Failure

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Continuous Integration", "Build Process", "Continuous Deployment"]
    types:
      - completed

jobs:
  send_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send failure notification via email
        if: failure()
        run: |
          echo "Subject: Build Failed Notification" > /tmp/email.txt
          echo "The build of your project has failed. Please check the logs for details." >> /tmp/email.txt
          msmtp --host=${{ secrets.SMTP_SERVER }} --port=${{ secrets.SMTP_PORT }} --user=${{ secrets.SMTP_USER }} --passwordeval="echo ${{ secrets.SMTP_PASSWORD }}" --from=${{ secrets.EMAIL_FROM }} --to=${{ secrets.EMAIL_TO }} < /tmp/email.txt
