name: Release Process

on:
  workflow_dispatch:
  push:
    tags:
      - '**'

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Create new release tag
        run: |
          echo "Creating new release..."
          git tag -a v$(date +%Y%m%d%H%M%S) -m "New release"
          # Отправка тега на GitHub
          git push origin --tags

      - name: Create release in GitHub
        run: |
          echo "Creating release on GitHub..."
          TAG_NAME=$(git describe --tags)
          BODY="Release created with tag $TAG_NAME"
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d '{"tag_name": "'"$TAG_NAME"'", "name": "'"$TAG_NAME"'", "body": "'"$BODY"'", "draft": false, "prerelease": false}' \
            https://api.github.com/repos/${{ github.repository }}/releases
