name: Release Process

on:
  push:
    tags:
      - '*'

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create release
        run: |
          echo "Creating new release..."
          # Пример команды для публикации релиза в GitHub
          git tag -a v$(date +%Y%m%d%H%M%S) -m "New release"
          git push origin --tags
